# Generated by IBM TransformationAdvisor
# Fri Nov 27 19:14:01 UTC 2021

FROM ibmcom/websphere-traditional:latest-ubi

# put app and scripts and properties in /work/config
# put external library (e.g db driver) in /work/config/lib
COPY --chown=was:root modresorts-2.0.war /work/config/modresorts-2.0.war
COPY --chown=was:root ./src/config /work/config
COPY --chown=was:root ./lib /work/config/lib
EXPOSE 9080
EXPOSE 9060
EXPOSE 9043
EXPOSE 9443
RUN sh -xv /work/configure.sh "/work/config/install_app.py ADMIN oracle jdbc:oracle:thin:@//docker-oracle-xe:1521/XE 31939" 
